version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "/"
      - "/cmd/xk6-s3"
    schedule:
      interval: monthly
    groups:
      aws-sdk-go-v2:
        patterns:
          - "github.com/aws/aws-sdk-go-v2*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
